### ISSUE TITLE
Once created, strings cannot be updated

### ISSUE THREAD

**Issue by wowczarek** [Kst-plot/kst#14]
Looks like this has not changed since early 2.0.x.

Whenever I create a string (I use this for labels etc.), it cannot be changed afterwards.

To reproduce:

Create->String->[x] Generate->enter value, OK
data manager -> edit string, change, OK.

The original value remains. The "apply" button is never activated in the edit dialog when the value is changed.

The only way to change strings is to edit the XML source.

**Comment by net147** [comment]
Fixed by https://github.com/Kst-plot/kst/pull/17

**Comment by wowczarek** [comment]
Nice one, thank you!
