### ISSUE TITLE
Some png files cause "too far back" error messages

### ISSUE THREAD

**Issue by DeadParrot** [Kst-plot/kst#4]
A few of the png files in src/images cause this error message on the console at run time (running 2.0.8 on Fedora 23):

```
libpng error: IDAT: invalid distance too far back
```

The png files causing this appear to be:

```
kst_error_2.png
hi32-mime-kst.png
kst.png
kst_error_1.png
unused/kst_imagenew.png
unused/kst_pluginnew.png
unused/kst_eventnew.png
```

I tried the fix from http://archscientist.altervista.org/blog/how-to-solve-libpng-error-idat-invalid-distance-too-far-back/ using `optipng` but it seems to have erased the lower half of the images in addition to eliminating the error message, so I can't push those up to a branch.

**Comment by VikingsCat** [comment]
Found the same problem with Raspbian GNU/Linux 9.4 (stretch).
How to identify the problematic files?

**Comment by netterfield** [comment]
This has been fixed for a while.  Closing.
